version: "2"
services:
  web:
    image: youls/web-app
    ports:
      - "5000:5000"
    depends_on: 
      - redis
    volumes: 
      - .:/code 
    environment: 
      FLASK_ENV: development
  redis:
    image: redis:alpine